import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { cn } from "@/src/lib/utils";
import { Navbar } from "@/src/components/layout/Navbar";
import { Footer } from "@/src/components/layout/Footer";
import { Spacing } from "./_components/Spacing";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tous Albatros",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={cn(inter.className, "h-full")}>
        <Providers>
          <Navbar />
          <Spacing size="md" />
          {children}
          <Spacing size="md" />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
